server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

pay:
  environment: ${PAY_ENVIRONMENT:local}

spring:
  application:
    name: sbp-authpay-mock
  profiles:
    default: local
  lifecycle:
    timeout-per-shutdown-phase: 30s
  config:
    import:
      - optional:vault://
      - optional:configserver:${CONFIG_SERVER_URL:http://pay-payconfig-server:8080}
  cloud:
    config:
      enabled: ${CONFIG_SERVER_ENABLED:false}
      label: ${CONFIG_SERVER_LABEL:${pay.environment}}
      username: ${CONFIG_CLIENT_USERNAME:}
      password: ${CONFIG_CLIENT_PASSWORD:}
    vault:
      enabled: ${VAULT_ENABLED:false}
      kv:
        backend: ${VAULT_KV_BACKEND:pay}
        default-context: ""
        application-name: ${VAULT_KV_CONTEXTS:${pay.environment}/sbp-authpay-mock}
        profiles: []

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: sbp-authpay-mock
